version: '3'

services:
  eval:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ".:/api"
    tty: true
    environment:
      FLASK_APP: server.py
      FLASK_ENV: development
      TZ: Asia/Tokyo
    command: flask run --host 0.0.0.0 --port 5000